services:
  db_measurements:
    container_name: db_measurements
    image: "postgres:16"
    volumes :
      - postgres:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env.postgres
    ports:
      - "5433:5432"

  redis:
    container_name: redis
    image: redis:alpine

  app_sidekiq:
    build:
      dockerfile: docker/Dockerfile
      context: .
    volumes:
      - .:/app
    command: bundle exec sidekiq -q gps_measurements,2
    container_name: app_sidekiq
    env_file:
      - .env
    depends_on:
      - redis

  app_backend:
    platform: linux/x86_64
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: bundle exec rails s -p 8080 -b 0.0.0.0 -e development
    container_name: app_backend
    env_file:
      - .env
    depends_on:
      - db_measurements
      - app_sidekiq

volumes:
    postgres:
